// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/loan/module/payment/internal/usecase (interfaces: MutationUsecase)
//
// Generated by this command:
//
//	mockgen -destination=mock/mutation_usecase.go -package=mock example.com/loan/module/payment/internal/usecase MutationUsecase
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/loan/module/payment/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMutationUsecase is a mock of MutationUsecase interface.
type MockMutationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMutationUsecaseMockRecorder
	isgomock struct{}
}

// MockMutationUsecaseMockRecorder is the mock recorder for MockMutationUsecase.
type MockMutationUsecaseMockRecorder struct {
	mock *MockMutationUsecase
}

// NewMockMutationUsecase creates a new mock instance.
func NewMockMutationUsecase(ctrl *gomock.Controller) *MockMutationUsecase {
	mock := &MockMutationUsecase{ctrl: ctrl}
	mock.recorder = &MockMutationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutationUsecase) EXPECT() *MockMutationUsecaseMockRecorder {
	return m.recorder
}

// Debit mocks base method.
func (m *MockMutationUsecase) Debit(ctx context.Context, mutation entity.Mutation) (entity.Mutation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Debit", ctx, mutation)
	ret0, _ := ret[0].(entity.Mutation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Debit indicates an expected call of Debit.
func (mr *MockMutationUsecaseMockRecorder) Debit(ctx, mutation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debit", reflect.TypeOf((*MockMutationUsecase)(nil).Debit), ctx, mutation)
}
