version: "3"
services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=loan-backend
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - ${MYSQL_PORT}:3306
