// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/loan/module/loan/internal/usecase (interfaces: LoanUsecase)
//
// Generated by this command:
//
//	mockgen -destination=mock/loan_usecase.go -package=mock example.com/loan/module/loan/internal/usecase LoanUsecase
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/loan/module/loan/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLoanUsecase is a mock of LoanUsecase interface.
type MockLoanUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLoanUsecaseMockRecorder
	isgomock struct{}
}

// MockLoanUsecaseMockRecorder is the mock recorder for MockLoanUsecase.
type MockLoanUsecaseMockRecorder struct {
	mock *MockLoanUsecase
}

// NewMockLoanUsecase creates a new mock instance.
func NewMockLoanUsecase(ctrl *gomock.Controller) *MockLoanUsecase {
	mock := &MockLoanUsecase{ctrl: ctrl}
	mock.recorder = &MockLoanUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanUsecase) EXPECT() *MockLoanUsecaseMockRecorder {
	return m.recorder
}

// GetOutstandingLoans mocks base method.
func (m *MockLoanUsecase) GetOutstandingLoans(ctx context.Context, loanID string) (entity.GetOutstandingLoansResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutstandingLoans", ctx, loanID)
	ret0, _ := ret[0].(entity.GetOutstandingLoansResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutstandingLoans indicates an expected call of GetOutstandingLoans.
func (mr *MockLoanUsecaseMockRecorder) GetOutstandingLoans(ctx, loanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutstandingLoans", reflect.TypeOf((*MockLoanUsecase)(nil).GetOutstandingLoans), ctx, loanID)
}
