// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/loan/module/payment/client (interfaces: PaymentService)
//
// Generated by this command:
//
//	mockgen -destination=mock/payment_service.go -package=mock example.com/loan/module/payment/client PaymentService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	client "example.com/loan/module/payment/client"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
	isgomock struct{}
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// CreateAndPayMutation mocks base method.
func (m *MockPaymentService) CreateAndPayMutation(ctx context.Context, req client.CreateAndPayMutationRequest) (client.CreateAndPayMutationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndPayMutation", ctx, req)
	ret0, _ := ret[0].(client.CreateAndPayMutationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndPayMutation indicates an expected call of CreateAndPayMutation.
func (mr *MockPaymentServiceMockRecorder) CreateAndPayMutation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndPayMutation", reflect.TypeOf((*MockPaymentService)(nil).CreateAndPayMutation), ctx, req)
}
