// Code generated by "enumer -type=AccountStatus -trimprefix=AccountStatus -transform=kebab"; DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"
)

const _AccountStatusName = "unspecifiedinactiveactivefrozen"

var _AccountStatusIndex = [...]uint8{0, 11, 19, 25, 31}

const _AccountStatusLowerName = "unspecifiedinactiveactivefrozen"

func (i AccountStatus) String() string {
	if i < 0 || i >= AccountStatus(len(_AccountStatusIndex)-1) {
		return fmt.Sprintf("AccountStatus(%d)", i)
	}
	return _AccountStatusName[_AccountStatusIndex[i]:_AccountStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AccountStatusNoOp() {
	var x [1]struct{}
	_ = x[AccountStatusUnspecified-(0)]
	_ = x[AccountStatusInactive-(1)]
	_ = x[AccountStatusActive-(2)]
	_ = x[AccountStatusFrozen-(3)]
}

var _AccountStatusValues = []AccountStatus{AccountStatusUnspecified, AccountStatusInactive, AccountStatusActive, AccountStatusFrozen}

var _AccountStatusNameToValueMap = map[string]AccountStatus{
	_AccountStatusName[0:11]:       AccountStatusUnspecified,
	_AccountStatusLowerName[0:11]:  AccountStatusUnspecified,
	_AccountStatusName[11:19]:      AccountStatusInactive,
	_AccountStatusLowerName[11:19]: AccountStatusInactive,
	_AccountStatusName[19:25]:      AccountStatusActive,
	_AccountStatusLowerName[19:25]: AccountStatusActive,
	_AccountStatusName[25:31]:      AccountStatusFrozen,
	_AccountStatusLowerName[25:31]: AccountStatusFrozen,
}

var _AccountStatusNames = []string{
	_AccountStatusName[0:11],
	_AccountStatusName[11:19],
	_AccountStatusName[19:25],
	_AccountStatusName[25:31],
}

// AccountStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AccountStatusString(s string) (AccountStatus, error) {
	if val, ok := _AccountStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AccountStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AccountStatus values", s)
}

// AccountStatusValues returns all values of the enum
func AccountStatusValues() []AccountStatus {
	return _AccountStatusValues
}

// AccountStatusStrings returns a slice of all String values of the enum
func AccountStatusStrings() []string {
	strs := make([]string, len(_AccountStatusNames))
	copy(strs, _AccountStatusNames)
	return strs
}

// IsAAccountStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AccountStatus) IsAAccountStatus() bool {
	for _, v := range _AccountStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
