// Code generated by "enumer -type=MutationType -trimprefix=MutationType -transform=kebab"; DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"
)

const _MutationTypeName = "unspecifiedrepayment"

var _MutationTypeIndex = [...]uint8{0, 11, 20}

const _MutationTypeLowerName = "unspecifiedrepayment"

func (i MutationType) String() string {
	if i < 0 || i >= MutationType(len(_MutationTypeIndex)-1) {
		return fmt.Sprintf("MutationType(%d)", i)
	}
	return _MutationTypeName[_MutationTypeIndex[i]:_MutationTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MutationTypeNoOp() {
	var x [1]struct{}
	_ = x[MutationTypeUnspecified-(0)]
	_ = x[MutationTypeRepayment-(1)]
}

var _MutationTypeValues = []MutationType{MutationTypeUnspecified, MutationTypeRepayment}

var _MutationTypeNameToValueMap = map[string]MutationType{
	_MutationTypeName[0:11]:       MutationTypeUnspecified,
	_MutationTypeLowerName[0:11]:  MutationTypeUnspecified,
	_MutationTypeName[11:20]:      MutationTypeRepayment,
	_MutationTypeLowerName[11:20]: MutationTypeRepayment,
}

var _MutationTypeNames = []string{
	_MutationTypeName[0:11],
	_MutationTypeName[11:20],
}

// MutationTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MutationTypeString(s string) (MutationType, error) {
	if val, ok := _MutationTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MutationTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MutationType values", s)
}

// MutationTypeValues returns all values of the enum
func MutationTypeValues() []MutationType {
	return _MutationTypeValues
}

// MutationTypeStrings returns a slice of all String values of the enum
func MutationTypeStrings() []string {
	strs := make([]string, len(_MutationTypeNames))
	copy(strs, _MutationTypeNames)
	return strs
}

// IsAMutationType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MutationType) IsAMutationType() bool {
	for _, v := range _MutationTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
