// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/loan/module/payment/internal/repository (interfaces: MutationRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mutation_repository.go -package=mock example.com/loan/module/payment/internal/repository MutationRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/loan/module/payment/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMutationRepository is a mock of MutationRepository interface.
type MockMutationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMutationRepositoryMockRecorder
	isgomock struct{}
}

// MockMutationRepositoryMockRecorder is the mock recorder for MockMutationRepository.
type MockMutationRepositoryMockRecorder struct {
	mock *MockMutationRepository
}

// NewMockMutationRepository creates a new mock instance.
func NewMockMutationRepository(ctrl *gomock.Controller) *MockMutationRepository {
	mock := &MockMutationRepository{ctrl: ctrl}
	mock.recorder = &MockMutationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutationRepository) EXPECT() *MockMutationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMutationRepository) Create(ctx context.Context, mutation *entity.Mutation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, mutation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMutationRepositoryMockRecorder) Create(ctx, mutation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMutationRepository)(nil).Create), ctx, mutation)
}

// Get mocks base method.
func (m *MockMutationRepository) Get(ctx context.Context, mutation entity.Mutation) (entity.Mutation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, mutation)
	ret0, _ := ret[0].(entity.Mutation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMutationRepositoryMockRecorder) Get(ctx, mutation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMutationRepository)(nil).Get), ctx, mutation)
}
