// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/loan/module/loan/internal/repository (interfaces: LoanBillingRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/loan_billing_repository.go -package=mock example.com/loan/module/loan/internal/repository LoanBillingRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/loan/module/loan/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLoanBillingRepository is a mock of LoanBillingRepository interface.
type MockLoanBillingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoanBillingRepositoryMockRecorder
	isgomock struct{}
}

// MockLoanBillingRepositoryMockRecorder is the mock recorder for MockLoanBillingRepository.
type MockLoanBillingRepositoryMockRecorder struct {
	mock *MockLoanBillingRepository
}

// NewMockLoanBillingRepository creates a new mock instance.
func NewMockLoanBillingRepository(ctrl *gomock.Controller) *MockLoanBillingRepository {
	mock := &MockLoanBillingRepository{ctrl: ctrl}
	mock.recorder = &MockLoanBillingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanBillingRepository) EXPECT() *MockLoanBillingRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockLoanBillingRepository) BulkCreate(ctx context.Context, billings []entity.LoanBilling) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, billings)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockLoanBillingRepositoryMockRecorder) BulkCreate(ctx, billings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockLoanBillingRepository)(nil).BulkCreate), ctx, billings)
}

// GetByID mocks base method.
func (m *MockLoanBillingRepository) GetByID(ctx context.Context, billingID string) (entity.LoanBilling, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, billingID)
	ret0, _ := ret[0].(entity.LoanBilling)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLoanBillingRepositoryMockRecorder) GetByID(ctx, billingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLoanBillingRepository)(nil).GetByID), ctx, billingID)
}

// SumOutstandingLoans mocks base method.
func (m *MockLoanBillingRepository) SumOutstandingLoans(ctx context.Context, loanID string) (entity.GetOutstandingLoansResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumOutstandingLoans", ctx, loanID)
	ret0, _ := ret[0].(entity.GetOutstandingLoansResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumOutstandingLoans indicates an expected call of SumOutstandingLoans.
func (mr *MockLoanBillingRepositoryMockRecorder) SumOutstandingLoans(ctx, loanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumOutstandingLoans", reflect.TypeOf((*MockLoanBillingRepository)(nil).SumOutstandingLoans), ctx, loanID)
}

// Update mocks base method.
func (m *MockLoanBillingRepository) Update(ctx context.Context, billing entity.LoanBilling) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, billing)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLoanBillingRepositoryMockRecorder) Update(ctx, billing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoanBillingRepository)(nil).Update), ctx, billing)
}
