// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/loan/module/loan/internal/repository (interfaces: LoanRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/loan_repository.go -package=mock example.com/loan/module/loan/internal/repository LoanRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/loan/module/loan/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLoanRepository is a mock of LoanRepository interface.
type MockLoanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoanRepositoryMockRecorder
	isgomock struct{}
}

// MockLoanRepositoryMockRecorder is the mock recorder for MockLoanRepository.
type MockLoanRepositoryMockRecorder struct {
	mock *MockLoanRepository
}

// NewMockLoanRepository creates a new mock instance.
func NewMockLoanRepository(ctrl *gomock.Controller) *MockLoanRepository {
	mock := &MockLoanRepository{ctrl: ctrl}
	mock.recorder = &MockLoanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanRepository) EXPECT() *MockLoanRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLoanRepository) Create(ctx context.Context, loan *entity.Loan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, loan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLoanRepositoryMockRecorder) Create(ctx, loan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLoanRepository)(nil).Create), ctx, loan)
}

// GetByID mocks base method.
func (m *MockLoanRepository) GetByID(ctx context.Context, loanID string) (entity.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, loanID)
	ret0, _ := ret[0].(entity.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLoanRepositoryMockRecorder) GetByID(ctx, loanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLoanRepository)(nil).GetByID), ctx, loanID)
}

// Update mocks base method.
func (m *MockLoanRepository) Update(ctx context.Context, loan entity.Loan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, loan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLoanRepositoryMockRecorder) Update(ctx, loan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoanRepository)(nil).Update), ctx, loan)
}
