// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/loan/module/loan/internal/repository (interfaces: RepaymentRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/repayment_repository.go -package=mock example.com/loan/module/loan/internal/repository RepaymentRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/loan/module/loan/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepaymentRepository is a mock of RepaymentRepository interface.
type MockRepaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockRepaymentRepositoryMockRecorder is the mock recorder for MockRepaymentRepository.
type MockRepaymentRepositoryMockRecorder struct {
	mock *MockRepaymentRepository
}

// NewMockRepaymentRepository creates a new mock instance.
func NewMockRepaymentRepository(ctrl *gomock.Controller) *MockRepaymentRepository {
	mock := &MockRepaymentRepository{ctrl: ctrl}
	mock.recorder = &MockRepaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepaymentRepository) EXPECT() *MockRepaymentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepaymentRepository) Create(ctx context.Context, repayment *entity.Repayment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, repayment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepaymentRepositoryMockRecorder) Create(ctx, repayment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepaymentRepository)(nil).Create), ctx, repayment)
}

// Update mocks base method.
func (m *MockRepaymentRepository) Update(ctx context.Context, repayment entity.Repayment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, repayment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepaymentRepositoryMockRecorder) Update(ctx, repayment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepaymentRepository)(nil).Update), ctx, repayment)
}
