// Code generated by "enumer -type=LoanStatus -trimprefix=LoanStatus -transform=kebab"; DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"
)

const _LoanStatusName = "unspecifiedproposedapprovedinvesteddisbursed"

var _LoanStatusIndex = [...]uint8{0, 11, 19, 27, 35, 44}

const _LoanStatusLowerName = "unspecifiedproposedapprovedinvesteddisbursed"

func (i LoanStatus) String() string {
	if i < 0 || i >= LoanStatus(len(_LoanStatusIndex)-1) {
		return fmt.Sprintf("LoanStatus(%d)", i)
	}
	return _LoanStatusName[_LoanStatusIndex[i]:_LoanStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LoanStatusNoOp() {
	var x [1]struct{}
	_ = x[LoanStatusUnspecified-(0)]
	_ = x[LoanStatusProposed-(1)]
	_ = x[LoanStatusApproved-(2)]
	_ = x[LoanStatusInvested-(3)]
	_ = x[LoanStatusDisbursed-(4)]
}

var _LoanStatusValues = []LoanStatus{LoanStatusUnspecified, LoanStatusProposed, LoanStatusApproved, LoanStatusInvested, LoanStatusDisbursed}

var _LoanStatusNameToValueMap = map[string]LoanStatus{
	_LoanStatusName[0:11]:       LoanStatusUnspecified,
	_LoanStatusLowerName[0:11]:  LoanStatusUnspecified,
	_LoanStatusName[11:19]:      LoanStatusProposed,
	_LoanStatusLowerName[11:19]: LoanStatusProposed,
	_LoanStatusName[19:27]:      LoanStatusApproved,
	_LoanStatusLowerName[19:27]: LoanStatusApproved,
	_LoanStatusName[27:35]:      LoanStatusInvested,
	_LoanStatusLowerName[27:35]: LoanStatusInvested,
	_LoanStatusName[35:44]:      LoanStatusDisbursed,
	_LoanStatusLowerName[35:44]: LoanStatusDisbursed,
}

var _LoanStatusNames = []string{
	_LoanStatusName[0:11],
	_LoanStatusName[11:19],
	_LoanStatusName[19:27],
	_LoanStatusName[27:35],
	_LoanStatusName[35:44],
}

// LoanStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LoanStatusString(s string) (LoanStatus, error) {
	if val, ok := _LoanStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LoanStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LoanStatus values", s)
}

// LoanStatusValues returns all values of the enum
func LoanStatusValues() []LoanStatus {
	return _LoanStatusValues
}

// LoanStatusStrings returns a slice of all String values of the enum
func LoanStatusStrings() []string {
	strs := make([]string, len(_LoanStatusNames))
	copy(strs, _LoanStatusNames)
	return strs
}

// IsALoanStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LoanStatus) IsALoanStatus() bool {
	for _, v := range _LoanStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
