// Code generated by "enumer -type=LoanBillingStatus -trimprefix=LoanBillingStatus -transform=kebab"; DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"
)

const _LoanBillingStatusName = "unspecifiedcreatedpaidoverdue"

var _LoanBillingStatusIndex = [...]uint8{0, 11, 18, 22, 29}

const _LoanBillingStatusLowerName = "unspecifiedcreatedpaidoverdue"

func (i LoanBillingStatus) String() string {
	if i < 0 || i >= LoanBillingStatus(len(_LoanBillingStatusIndex)-1) {
		return fmt.Sprintf("LoanBillingStatus(%d)", i)
	}
	return _LoanBillingStatusName[_LoanBillingStatusIndex[i]:_LoanBillingStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LoanBillingStatusNoOp() {
	var x [1]struct{}
	_ = x[LoanBillingStatusUnspecified-(0)]
	_ = x[LoanBillingStatusCreated-(1)]
	_ = x[LoanBillingStatusPaid-(2)]
	_ = x[LoanBillingStatusOverdue-(3)]
}

var _LoanBillingStatusValues = []LoanBillingStatus{LoanBillingStatusUnspecified, LoanBillingStatusCreated, LoanBillingStatusPaid, LoanBillingStatusOverdue}

var _LoanBillingStatusNameToValueMap = map[string]LoanBillingStatus{
	_LoanBillingStatusName[0:11]:       LoanBillingStatusUnspecified,
	_LoanBillingStatusLowerName[0:11]:  LoanBillingStatusUnspecified,
	_LoanBillingStatusName[11:18]:      LoanBillingStatusCreated,
	_LoanBillingStatusLowerName[11:18]: LoanBillingStatusCreated,
	_LoanBillingStatusName[18:22]:      LoanBillingStatusPaid,
	_LoanBillingStatusLowerName[18:22]: LoanBillingStatusPaid,
	_LoanBillingStatusName[22:29]:      LoanBillingStatusOverdue,
	_LoanBillingStatusLowerName[22:29]: LoanBillingStatusOverdue,
}

var _LoanBillingStatusNames = []string{
	_LoanBillingStatusName[0:11],
	_LoanBillingStatusName[11:18],
	_LoanBillingStatusName[18:22],
	_LoanBillingStatusName[22:29],
}

// LoanBillingStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LoanBillingStatusString(s string) (LoanBillingStatus, error) {
	if val, ok := _LoanBillingStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LoanBillingStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LoanBillingStatus values", s)
}

// LoanBillingStatusValues returns all values of the enum
func LoanBillingStatusValues() []LoanBillingStatus {
	return _LoanBillingStatusValues
}

// LoanBillingStatusStrings returns a slice of all String values of the enum
func LoanBillingStatusStrings() []string {
	strs := make([]string, len(_LoanBillingStatusNames))
	copy(strs, _LoanBillingStatusNames)
	return strs
}

// IsALoanBillingStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LoanBillingStatus) IsALoanBillingStatus() bool {
	for _, v := range _LoanBillingStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
