// Code generated by "enumer -type=RepaymentStatus -trimprefix=RepaymentStatus -transform=kebab"; DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"
)

const _RepaymentStatusName = "unspecifiedcreatedpaid"

var _RepaymentStatusIndex = [...]uint8{0, 11, 18, 22}

const _RepaymentStatusLowerName = "unspecifiedcreatedpaid"

func (i RepaymentStatus) String() string {
	if i < 0 || i >= RepaymentStatus(len(_RepaymentStatusIndex)-1) {
		return fmt.Sprintf("RepaymentStatus(%d)", i)
	}
	return _RepaymentStatusName[_RepaymentStatusIndex[i]:_RepaymentStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RepaymentStatusNoOp() {
	var x [1]struct{}
	_ = x[RepaymentStatusUnspecified-(0)]
	_ = x[RepaymentStatusCreated-(1)]
	_ = x[RepaymentStatusPaid-(2)]
}

var _RepaymentStatusValues = []RepaymentStatus{RepaymentStatusUnspecified, RepaymentStatusCreated, RepaymentStatusPaid}

var _RepaymentStatusNameToValueMap = map[string]RepaymentStatus{
	_RepaymentStatusName[0:11]:       RepaymentStatusUnspecified,
	_RepaymentStatusLowerName[0:11]:  RepaymentStatusUnspecified,
	_RepaymentStatusName[11:18]:      RepaymentStatusCreated,
	_RepaymentStatusLowerName[11:18]: RepaymentStatusCreated,
	_RepaymentStatusName[18:22]:      RepaymentStatusPaid,
	_RepaymentStatusLowerName[18:22]: RepaymentStatusPaid,
}

var _RepaymentStatusNames = []string{
	_RepaymentStatusName[0:11],
	_RepaymentStatusName[11:18],
	_RepaymentStatusName[18:22],
}

// RepaymentStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RepaymentStatusString(s string) (RepaymentStatus, error) {
	if val, ok := _RepaymentStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RepaymentStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RepaymentStatus values", s)
}

// RepaymentStatusValues returns all values of the enum
func RepaymentStatusValues() []RepaymentStatus {
	return _RepaymentStatusValues
}

// RepaymentStatusStrings returns a slice of all String values of the enum
func RepaymentStatusStrings() []string {
	strs := make([]string, len(_RepaymentStatusNames))
	copy(strs, _RepaymentStatusNames)
	return strs
}

// IsARepaymentStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RepaymentStatus) IsARepaymentStatus() bool {
	for _, v := range _RepaymentStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
