// Code generated by "enumer -type=UserStatus -trimprefix=UserStatus -transform=kebab"; DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"
)

const _UserStatusName = "unspecifiedinactiveactivedelinquent"

var _UserStatusIndex = [...]uint8{0, 11, 19, 25, 35}

const _UserStatusLowerName = "unspecifiedinactiveactivedelinquent"

func (i UserStatus) String() string {
	if i < 0 || i >= UserStatus(len(_UserStatusIndex)-1) {
		return fmt.Sprintf("UserStatus(%d)", i)
	}
	return _UserStatusName[_UserStatusIndex[i]:_UserStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserStatusNoOp() {
	var x [1]struct{}
	_ = x[UserStatusUnspecified-(0)]
	_ = x[UserStatusInactive-(1)]
	_ = x[UserStatusActive-(2)]
	_ = x[UserStatusDelinquent-(3)]
}

var _UserStatusValues = []UserStatus{UserStatusUnspecified, UserStatusInactive, UserStatusActive, UserStatusDelinquent}

var _UserStatusNameToValueMap = map[string]UserStatus{
	_UserStatusName[0:11]:       UserStatusUnspecified,
	_UserStatusLowerName[0:11]:  UserStatusUnspecified,
	_UserStatusName[11:19]:      UserStatusInactive,
	_UserStatusLowerName[11:19]: UserStatusInactive,
	_UserStatusName[19:25]:      UserStatusActive,
	_UserStatusLowerName[19:25]: UserStatusActive,
	_UserStatusName[25:35]:      UserStatusDelinquent,
	_UserStatusLowerName[25:35]: UserStatusDelinquent,
}

var _UserStatusNames = []string{
	_UserStatusName[0:11],
	_UserStatusName[11:19],
	_UserStatusName[19:25],
	_UserStatusName[25:35],
}

// UserStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserStatusString(s string) (UserStatus, error) {
	if val, ok := _UserStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserStatus values", s)
}

// UserStatusValues returns all values of the enum
func UserStatusValues() []UserStatus {
	return _UserStatusValues
}

// UserStatusStrings returns a slice of all String values of the enum
func UserStatusStrings() []string {
	strs := make([]string, len(_UserStatusNames))
	copy(strs, _UserStatusNames)
	return strs
}

// IsAUserStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserStatus) IsAUserStatus() bool {
	for _, v := range _UserStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
